package com.paqueteria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntentoEntregaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentoEntregaAllPropertiesEquals(IntentoEntrega expected, IntentoEntrega actual) {
        assertIntentoEntregaAutoGeneratedPropertiesEquals(expected, actual);
        assertIntentoEntregaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentoEntregaAllUpdatablePropertiesEquals(IntentoEntrega expected, IntentoEntrega actual) {
        assertIntentoEntregaUpdatableFieldsEquals(expected, actual);
        assertIntentoEntregaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentoEntregaAutoGeneratedPropertiesEquals(IntentoEntrega expected, IntentoEntrega actual) {
        assertThat(actual)
            .as("Verify IntentoEntrega auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentoEntregaUpdatableFieldsEquals(IntentoEntrega expected, IntentoEntrega actual) {
        assertThat(actual)
            .as("Verify IntentoEntrega relevant properties")
            .satisfies(a -> assertThat(a.getFechaIntento()).as("check fechaIntento").isEqualTo(expected.getFechaIntento()))
            .satisfies(a -> assertThat(a.getResultado()).as("check resultado").isEqualTo(expected.getResultado()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getProximoIntento()).as("check proximoIntento").isEqualTo(expected.getProximoIntento()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentoEntregaUpdatableRelationshipsEquals(IntentoEntrega expected, IntentoEntrega actual) {
        assertThat(actual)
            .as("Verify IntentoEntrega relationships")
            .satisfies(a -> assertThat(a.getPaquete()).as("check paquete").isEqualTo(expected.getPaquete()));
    }
}
