package com.paqueteria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SeguimientoPaqueteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguimientoPaqueteAllPropertiesEquals(SeguimientoPaquete expected, SeguimientoPaquete actual) {
        assertSeguimientoPaqueteAutoGeneratedPropertiesEquals(expected, actual);
        assertSeguimientoPaqueteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguimientoPaqueteAllUpdatablePropertiesEquals(SeguimientoPaquete expected, SeguimientoPaquete actual) {
        assertSeguimientoPaqueteUpdatableFieldsEquals(expected, actual);
        assertSeguimientoPaqueteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguimientoPaqueteAutoGeneratedPropertiesEquals(SeguimientoPaquete expected, SeguimientoPaquete actual) {
        assertThat(actual)
            .as("Verify SeguimientoPaquete auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguimientoPaqueteUpdatableFieldsEquals(SeguimientoPaquete expected, SeguimientoPaquete actual) {
        assertThat(actual)
            .as("Verify SeguimientoPaquete relevant properties")
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getUbicacion()).as("check ubicacion").isEqualTo(expected.getUbicacion()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguimientoPaqueteUpdatableRelationshipsEquals(SeguimientoPaquete expected, SeguimientoPaquete actual) {
        assertThat(actual)
            .as("Verify SeguimientoPaquete relationships")
            .satisfies(a -> assertThat(a.getPaquete()).as("check paquete").isEqualTo(expected.getPaquete()));
    }
}
