package com.paqueteria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SucursalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalAllPropertiesEquals(Sucursal expected, Sucursal actual) {
        assertSucursalAutoGeneratedPropertiesEquals(expected, actual);
        assertSucursalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalAllUpdatablePropertiesEquals(Sucursal expected, Sucursal actual) {
        assertSucursalUpdatableFieldsEquals(expected, actual);
        assertSucursalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalAutoGeneratedPropertiesEquals(Sucursal expected, Sucursal actual) {
        assertThat(actual)
            .as("Verify Sucursal auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalUpdatableFieldsEquals(Sucursal expected, Sucursal actual) {
        assertThat(actual)
            .as("Verify Sucursal relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getPais()).as("check pais").isEqualTo(expected.getPais()))
            .satisfies(a -> assertThat(a.getCiudad()).as("check ciudad").isEqualTo(expected.getCiudad()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getLatitud()).as("check latitud").isEqualTo(expected.getLatitud()))
            .satisfies(a -> assertThat(a.getLongitud()).as("check longitud").isEqualTo(expected.getLongitud()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalUpdatableRelationshipsEquals(Sucursal expected, Sucursal actual) {
        // empty method
    }
}
