package com.paqueteria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ZonaEntregaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZonaEntregaAllPropertiesEquals(ZonaEntrega expected, ZonaEntrega actual) {
        assertZonaEntregaAutoGeneratedPropertiesEquals(expected, actual);
        assertZonaEntregaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZonaEntregaAllUpdatablePropertiesEquals(ZonaEntrega expected, ZonaEntrega actual) {
        assertZonaEntregaUpdatableFieldsEquals(expected, actual);
        assertZonaEntregaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZonaEntregaAutoGeneratedPropertiesEquals(ZonaEntrega expected, ZonaEntrega actual) {
        assertThat(actual)
            .as("Verify ZonaEntrega auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZonaEntregaUpdatableFieldsEquals(ZonaEntrega expected, ZonaEntrega actual) {
        assertThat(actual)
            .as("Verify ZonaEntrega relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZonaEntregaUpdatableRelationshipsEquals(ZonaEntrega expected, ZonaEntrega actual) {
        // empty method
    }
}
